plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'
}

android {
    compileSdk = 37
    defaultConfig {
        applicationId "com.oletob.rpncalc"
        minSdkVersion 24
        targetSdk 37
        versionCode 14
        versionName "26.08.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            applicationIdSuffix ".debug"
            debuggable true
            versionNameSuffix "-debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    buildFeatures {
        compose true
        buildConfig true
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.14'
    }

    flavorDimensions "default"
    productFlavors {
        dev {
            dimension "default"
            applicationIdSuffix ".dev"
            resValue "string", "app_name", "RPN Dev"
        }
        prod {
            dimension "default"
            resValue "string", "app_name", "RPN Calculator"

        }
    }
    namespace 'com.oletob.rpncalc'
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'

    // Compose BOM
    implementation platform('androidx.compose:compose-bom:2024.06.00')
    androidTestImplementation platform('androidx.compose:compose-bom:2024.06.00')

    // Compose UI
    implementation 'androidx.activity:activity-compose:1.9.1'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-core'

    // Lifecycle + Compose
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.4'

    // Navigation Compose
    implementation 'androidx.navigation:navigation-compose:2.7.7'

    // Hilt
    implementation "com.google.dagger:hilt-android:2.51.1"
    ksp "com.google.dagger:hilt-android-compiler:2.51.1"
    implementation 'androidx.hilt:hilt-navigation-compose:1.2.0'

    // Room Database
    def room_version = "2.6.1"
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    ksp "androidx.room:room-compiler:$room_version"

    testImplementation 'junit:junit:4.13.2'
}
